[book]
authors = ["weykon"]
language = "en"
multilingual = false
src = "src"
title = "Touch MdBook"

[output.html]
git-repository-url="https://github.com/weykon/touch-mdbook.git"
git-repository-icon = "fa-github"